# Generated by Django 3.0.6 on 2020-07-14 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200714_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.Listing'),
        ),
    ]
